kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30092
        hostPort: 30092
        protocol: TCP
      - containerPort: 30042
        hostPort: 30042
        protocol: TCP
      - containerPort: 30379
        hostPort: 30379
        protocol: TCP
      - containerPort: 30080
        hostPort: 30080
        protocol: TCP