apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
        - name: producer
          image:  redacted_information
          env:
            - name: bootstrap_servers
              value: "kafka:9092"
            - name: DB_URL
              value: "cassandra"
            - name: CACHE_URL
              value: "redis-cache-service"
